### ISSUE TITLE
Panic writing to overlay

### ISSUE THREAD

**Issue by jdm** [jdm/libmzx#17]
https://www.digitalmzx.com/show.php?id=883
```
Capturing board 2: lvl1
thread 'main' panicked at 'range end index 10074 out of range for slice of length 10000', /Users/jdm/src/libmzx/src/lib.rs:390:67
stack backtrace:
   0: rust_begin_unwind
             at /rustc/81dc88f88f92ba8ad7465f9cba10c12d3a7b70f1/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/81dc88f88f92ba8ad7465f9cba10c12d3a7b70f1/library/core/src/panicking.rs:85
   2: core::slice::slice_end_index_len_fail
             at /rustc/81dc88f88f92ba8ad7465f9cba10c12d3a7b70f1/library/core/src/slice/mod.rs:3152
   3: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index_mut
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3352
   4: core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3137
   5: <alloc::vec::Vec<T> as core::ops::index::IndexMut<I>>::index_mut
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec.rs:2024
   6: libmzx::Board::write_overlay
             at /Users/jdm/src/libmzx/src/lib.rs:390
   7: libmzx::robot::run_one_command
             at /Users/jdm/src/libmzx/src/robot.rs:1437
   8: libmzx::robot::update_robot
             at /Users/jdm/src/libmzx/src/robot.rs:390
   9: libmzx::board::update_board
             at /Users/jdm/src/libmzx/src/board.rs:178
  10: capture::run
             at ./capture/src/main.rs:124
  11: capture::main
             at ./capture/src/main.rs:203
  12: core::ops::function::FnOnce::call_once
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:233
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jdm** [comment]
Fixed by 268a11feb435bc5098673b786994386e62ab27e2
