### ISSUE TITLE
Panic rendering doors

### ISSUE THREAD

**Issue by jdm** [jdm/libmzx#52]
https://www.digitalmzx.com/show.php?id=698
```
Capturing board 1: Freaktown
thread 'main' panicked at 'internal error: entered unreachable code', /Users/jdm/src/libmzx/src/lib.rs:1396:14
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:497
   1: libmzx::door_from_param
             at /Users/jdm/src/libmzx/src/lib.rs:1396
   2: libmzx::render::char_from_id
             at /Users/jdm/src/libmzx/src/render.rs:730
   3: libmzx::render::render
             at /Users/jdm/src/libmzx/src/render.rs:130
   4: capture::render_game
             at ./capture/src/main.rs:198
   5: capture::run
             at ./capture/src/main.rs:153
   6: capture::main
             at ./capture/src/main.rs:220
   7: core::ops::function::FnOnce::call_once
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:233
```

**Comment by jdm** [comment]
This is #15.
