### ISSUE TITLE
Panic placing object on board

### ISSUE THREAD

**Issue by jdm** [jdm/libmzx#54]
https://www.digitalmzx.com/show.php?id=2154

```
godot:mzxscreen jdm$ RUST_BACKTRACE=1 ./random.sh a
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
     Running `target/debug/capture image.png output.json unzipped/KKbday3/KKBDAY3.mzx`
Capturing board 1: gameplay
thread 'main' panicked at 'index out of bounds: the len is 4160 but the index is 4160', /Users/jdm/src/libmzx/src/lib.rs:445:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/81dc88f88f92ba8ad7465f9cba10c12d3a7b70f1/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/81dc88f88f92ba8ad7465f9cba10c12d3a7b70f1/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /rustc/81dc88f88f92ba8ad7465f9cba10c12d3a7b70f1/library/core/src/panicking.rs:62
   3: <usize as core::slice::SliceIndex<[T]>>::index
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3285
   4: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3126
   5: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec.rs:2012
   6: libmzx::Board::put_at
             at /Users/jdm/src/libmzx/src/lib.rs:445
   7: libmzx::board::put_at
             at /Users/jdm/src/libmzx/src/board.rs:112
   8: libmzx::board::put_thing
             at /Users/jdm/src/libmzx/src/board.rs:101
   9: libmzx::robot::run_one_command
             at /Users/jdm/src/libmzx/src/robot.rs:1480
  10: libmzx::robot::update_robot
             at /Users/jdm/src/libmzx/src/robot.rs:413
  11: libmzx::board::update_board
             at /Users/jdm/src/libmzx/src/board.rs:186
  12: capture::run
             at ./capture/src/main.rs:141
  13: capture::main
             at ./capture/src/main.rs:220
  14: core::ops::function::FnOnce::call_once
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:233
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jdm** [comment]
Fixed by 615dae20f2d82a2bab6d19cb089ada5225b55d56
