### ISSUE TITLE
Panic loading robot's walk direction

### ISSUE THREAD

**Issue by jdm** [jdm/libmzx#81]
```
thread 'main' panicked at 'invalid direction value: 140', /Users/jdm/src/libmzx/src/lib.rs:2706:47
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/option.rs:1260:5
   3: core::option::Option<T>::expect
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: libmzx::get_direction
             at /Users/jdm/src/libmzx/src/lib.rs:2706:14
   5: libmzx::load_robot
             at /Users/jdm/src/libmzx/src/lib.rs:2767:26
   6: core::ops::function::Fn::call
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
   7: libmzx::get_objects
             at /Users/jdm/src/libmzx/src/lib.rs:2654:36
   8: libmzx::load_board
             at /Users/jdm/src/libmzx/src/lib.rs:2971:32
   9: libmzx::load_world
             at /Users/jdm/src/libmzx/src/lib.rs:3284:13
  10: capture::run
             at ./capture/src/main.rs:63:27
  11: capture::main
             at ./capture/src/main.rs:223:9
  12: core::ops::function::FnOnce::call_once
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

https://github.com/jdm/libmzx/blob/7d38fc0147448770b6eb3a15c995b92ec8e6ae99/src/lib.rs#L2767

**Comment by jdm** [comment]
https://www.digitalmzx.com/show.php?id=1484
