### ISSUE TITLE
Robot position isn't updated

### ISSUE THREAD

**Issue by jdm** [jdm/libmzx#88]
https://www.digitalmzx.com/show.php?id=2036
```
Capturing board 25: Phosphor Cavern
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Coordinate(131, 81)`,
 right: `Coordinate(96, 9)`: robot Board(170)', /Users/jdm/src/libmzx/src/board.rs:194:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/panicking.rs:92:14
   2: libmzx::board::update_board
             at /Users/jdm/src/libmzx/src/board.rs:194:21
   3: capture::run
             at ./capture/src/main.rs:145:17
   4: capture::main
             at ./capture/src/main.rs:223:9
   5: core::ops::function::FnOnce::call_once
             at /Users/jdm/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jdm** [comment]
Something is wrong with the copyrobot implementation and the eventual robot position.
