### ISSUE TITLE
overflow when moving robot

### ISSUE THREAD

**Issue by jdm** [jdm/libmzx#92]
https://www.digitalmzx.com/show.php?id=1978
```
     Running `target/debug/capture image.png output.json unzipped/ddl/ddl1.mzx`
Capturing board 36: gtown

thread 'main' panicked at 'attempt to multiply with overflow', /Users/jdm/src/libmzx/src/lib.rs:494:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5dc8789e300930751a78996da0fa906be5a344a2/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/5dc8789e300930751a78996da0fa906be5a344a2/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/5dc8789e300930751a78996da0fa906be5a344a2/library/core/src/panicking.rs:50:5
   3: libmzx::Board::move_level_to
             at /Users/jdm/src/libmzx/src/lib.rs:494:24
   4: libmzx::board::move_level_to
             at /Users/jdm/src/libmzx/src/board.rs:132:5
   5: libmzx::robot::move_robot
             at /Users/jdm/src/libmzx/src/robot.rs:93:13
   6: libmzx::robot::run_one_command
             at /Users/jdm/src/libmzx/src/robot.rs:1344:25
   7: libmzx::robot::update_robot
             at /Users/jdm/src/libmzx/src/robot.rs:475:15
   8: libmzx::board::update_board
             at /Users/jdm/src/libmzx/src/board.rs:197:34
   9: capture::run
             at ./capture/src/main.rs:145:17
  10: capture::main
             at ./capture/src/main.rs:223:9
  11: core::ops::function::FnOnce::call_once
             at /rustc/5dc8789e300930751a78996da0fa906be5a344a2/library/core/src/ops/function.rs:227:5
```

**Comment by jdm** [comment]
https://github.com/jdm/libmzx/blob/d602226c82770194417b43a7d4945d22c1e1e313/src/lib.rs#L494
