### ISSUE TITLE
Panic rendering sensor in chuck's abode

### ISSUE THREAD

**Issue by jdm** [jdm/libmzx#99]
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/jdm/src/libmzx/src/render.rs:909:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5dc8789e300930751a78996da0fa906be5a344a2/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/5dc8789e300930751a78996da0fa906be5a344a2/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/5dc8789e300930751a78996da0fa906be5a344a2/library/core/src/panicking.rs:69:5
   3: libmzx::render::char_from_id
             at /Users/jdm/src/libmzx/src/render.rs:909:33
   4: libmzx::render::render
             at /Users/jdm/src/libmzx/src/render.rs:130:13
   5: mzxplay::game::render_game
             at ./src/game.rs:27:5
   6: <mzxplay::game::PlayState as mzxplay::GameState>::render
             at ./src/game.rs:196:9
   7: mzxplay::run
             at ./src/main.rs:228:13
   8: mzxplay::main
             at ./src/main.rs:255:9
   9: core::ops::function::FnOnce::call_once
             at /rustc/5dc8789e300930751a78996da0fa906be5a344a2/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jdm** [comment]
Fixed by https://github.com/jdm/libmzx/commit/e199168f6937eb1426da1b16f01f2e187cf97c97.
